name: Publish GitHub Package

on:
  push:
    branches:
      - main

jobs:
  publish-github-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: minor
          minor-wording: 'add,Adds,new'
          major-wording: 'MAJOR,cut-major'
          patch-wording: 'patch,fixes' # Providing patch-wording will override commits
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_PACKAGE_TOKEN }}
